// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace APIMeow.Migrations
{
    [DbContext(typeof(DBMeownagement))]
    [Migration("20250915145847_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Meownagement")
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("APIMeow.Models.MetaCofrinhoTransacao", b =>
                {
                    b.Property<int>("IdRel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRel"));

                    b.Property<int?>("IdCofrinho")
                        .HasColumnType("integer");

                    b.Property<int?>("IdMeta")
                        .HasColumnType("integer");

                    b.Property<int>("IdTransacao")
                        .HasColumnType("integer");

                    b.HasKey("IdRel");

                    b.HasIndex("IdTransacao");

                    b.ToTable("MetaCofrinhoTransacao", "Meownagement");
                });

            modelBuilder.Entity("Classificacao", b =>
                {
                    b.Property<int>("IdClassificacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdClassificacao"));

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdClassificacao");

                    b.ToTable("Classificacao", "Meownagement");
                });

            modelBuilder.Entity("Cofrinho", b =>
                {
                    b.Property<int>("IdCofrinho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCofrinho"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataTermino")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DinheiroEconomizado")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Economia")
                        .HasColumnType("numeric");

                    b.Property<char>("Feita")
                        .HasColumnType("character(1)");

                    b.Property<int>("IdClassificacao")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QtsMoedas")
                        .HasColumnType("integer");

                    b.HasKey("IdCofrinho");

                    b.HasIndex("IdClassificacao");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Cofrinho", "Meownagement");
                });

            modelBuilder.Entity("Comentario", b =>
                {
                    b.Property<int>("IdComentario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdComentario"));

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Deslikes")
                        .HasColumnType("integer");

                    b.Property<int>("IdPost")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<int>("Likes")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdComentario");

                    b.HasIndex("IdPost");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Comentario", "Meownagement");
                });

            modelBuilder.Entity("Gatos", b =>
                {
                    b.Property<int>("IdGato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdGato"));

                    b.Property<int>("CodPaleta")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeImagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Raridade")
                        .HasColumnType("integer");

                    b.HasKey("IdGato");

                    b.ToTable("Gatos", "Meownagement");
                });

            modelBuilder.Entity("LoginDiario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<int>("IdLogin")
                        .HasColumnType("integer");

                    b.Property<int>("NumSequencia")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UltimoLogin")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdUsuario");

                    b.ToTable("LoginDiario", "Meownagement");
                });

            modelBuilder.Entity("Metas", b =>
                {
                    b.Property<int>("IdMeta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMeta"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataTermino")
                        .HasColumnType("timestamp with time zone");

                    b.Property<char>("Feita")
                        .HasColumnType("character(1)");

                    b.Property<decimal>("GastoLimite")
                        .HasColumnType("numeric");

                    b.Property<int>("IdClassificacao")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QtsMoedas")
                        .HasColumnType("integer");

                    b.HasKey("IdMeta");

                    b.HasIndex("IdClassificacao");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Metas", "Meownagement");
                });

            modelBuilder.Entity("Post", b =>
                {
                    b.Property<int>("IdPost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPost"));

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Deslikes")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<int>("Likes")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdPost");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Post", "Meownagement");
                });

            modelBuilder.Entity("Recorrencia", b =>
                {
                    b.Property<int>("IdRecorrencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRecorrencia"));

                    b.Property<int>("QtsAnos")
                        .HasColumnType("integer");

                    b.Property<int>("QtsDias")
                        .HasColumnType("integer");

                    b.Property<int>("QtsMeses")
                        .HasColumnType("integer");

                    b.HasKey("IdRecorrencia");

                    b.ToTable("Recorrencia", "Meownagement");
                });

            modelBuilder.Entity("Transacao", b =>
                {
                    b.Property<int>("IdTransacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTransacao"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataFinalizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<char>("Feita")
                        .HasColumnType("character(1)");

                    b.Property<int>("IdClassificacao")
                        .HasColumnType("integer");

                    b.Property<int?>("IdRecorrencia")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("QuantiaDinheiro")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SaldoAtual")
                        .HasColumnType("numeric");

                    b.HasKey("IdTransacao");

                    b.HasIndex("IdClassificacao");

                    b.HasIndex("IdRecorrencia");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Transacao", "Meownagement");
                });

            modelBuilder.Entity("Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Biografia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Pontos")
                        .HasColumnType("integer");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("numeric");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuario", "Meownagement");
                });

            modelBuilder.Entity("UsuarioGato", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<int>("IdGato")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<int>("Copias")
                        .HasColumnType("integer");

                    b.Property<char>("Equipado")
                        .HasColumnType("character(1)");

                    b.HasKey("IdUsuario", "IdGato");

                    b.HasIndex("IdGato");

                    b.ToTable("UsuarioGato", "Meownagement");
                });

            modelBuilder.Entity("APIMeow.Models.MetaCofrinhoTransacao", b =>
                {
                    b.HasOne("Transacao", "Transacao")
                        .WithMany()
                        .HasForeignKey("IdTransacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transacao");
                });

            modelBuilder.Entity("Cofrinho", b =>
                {
                    b.HasOne("Classificacao", "Classificacao")
                        .WithMany()
                        .HasForeignKey("IdClassificacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classificacao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Comentario", b =>
                {
                    b.HasOne("Post", "Post")
                        .WithMany("Comentarios")
                        .HasForeignKey("IdPost")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LoginDiario", b =>
                {
                    b.HasOne("Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Metas", b =>
                {
                    b.HasOne("Classificacao", "Classificacao")
                        .WithMany("Metas")
                        .HasForeignKey("IdClassificacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classificacao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Post", b =>
                {
                    b.HasOne("Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Transacao", b =>
                {
                    b.HasOne("Classificacao", "Classificacao")
                        .WithMany()
                        .HasForeignKey("IdClassificacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recorrencia", "Recorrencia")
                        .WithMany()
                        .HasForeignKey("IdRecorrencia");

                    b.HasOne("Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classificacao");

                    b.Navigation("Recorrencia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("UsuarioGato", b =>
                {
                    b.HasOne("Gatos", "Gato")
                        .WithMany()
                        .HasForeignKey("IdGato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gato");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Classificacao", b =>
                {
                    b.Navigation("Metas");
                });

            modelBuilder.Entity("Post", b =>
                {
                    b.Navigation("Comentarios");
                });
#pragma warning restore 612, 618
        }
    }
}
